query productSearch(
  $query: String
  $map: String
  $facetQuery: String
  $facetMap: String
  $orderBy: String
  $priceRange: String
  $from: Int
  $to: Int
  $withFacets: Boolean = true
) {
  products(
    query: $query
    map: $map
    orderBy: $orderBy
    priceRange: $priceRange
    from: $from
    to: $to
  ) @context(provider: "vtex.search-graphql") {
    cacheId
    productId
    description
    productName
    linkText
    brand
    link
    items {
      itemId
      name
      nameComplete
      complementName
      ean
      referenceId {
        Key
        Value
      }
      measurementUnit
      unitMultiplier
      images {
        cacheId
        imageId
        imageLabel
        imageTag
        imageUrl
        imageText
      }
      sellers {
        sellerId
        sellerName
        commertialOffer {
          discountHighlights {
            name
          }
          Price
          ListPrice
          PriceWithoutDiscount
          RewardValue
          PriceValidUntil
          AvailableQuantity
        }
      }
    }
    productClusters {
      id
      name
    }
  }
  facets(query: $facetQuery, map: $facetMap)
    @include(if: $withFacets)
    @context(provider: "vtex.search-graphql") {
    departments {
      quantity
      name
      link
      linkEncoded
      map
      selected
      value
    }
    brands {
      quantity
      name
      link
      linkEncoded
      map
      selected
      value
    }
    specificationFilters {
      name
      facets {
        quantity
        name
        link
        linkEncoded
        map
        selected
        value
      }
    }
    categoriesTrees {
      id
      quantity
      name
      link
      href
      linkEncoded
      map
      selected
      value
      children {
        id
        quantity
        name
        link
        href
        linkEncoded
        map
        selected
        value
        children {
          id
          quantity
          name
          link
          href
          linkEncoded
          map
          selected
          value
        }
      }
    }
    priceRanges {
      quantity
      name
      link
      linkEncoded
      slug
      map
    }
    recordsFiltered
    # Backwards compatibility with search-result v3
    Departments {
      Quantity
      Name
      Link
    }
    Brands {
      Quantity
      Name
      Link
    }
    SpecificationFilters {
      name
      facets {
        Quantity
        Name
        Link
      }
    }
    CategoriesTrees {
      Id
      Quantity
      Name
      Link
      href
      name
      Children {
        Id
        Quantity
        Name
        Link
        href
        name
        Children {
          Id
          Quantity
          Name
          Link
          href
          name
        }
      }
    }
    PriceRanges {
      Quantity
      Name
      Link
      Slug
    }
  }
}
