query Product(
  $slug: String
  $identifier: ProductUniqueIdentifier
  $skipCategoryTree: Boolean = false
) {
  product(slug: $slug, identifier: $identifier)
    @context(provider: "vtex.search-graphql") {
    cacheId
    productName
    productId
    description
    titleTag
    metaTagDescription
    linkText
    productReference
    categoryId
    categories
    categoryTree @skip(if: $skipCategoryTree) {
      id
      name
      href
    }
    brand
    brandId
    properties {
      name
      values
    }
    specificationGroups {
      name
      specifications {
        name
        values
      }
    }
    items {
      itemId
      name
      nameComplete
      complementName
      ean
      referenceId {
        Key
        Value
      }
      measurementUnit
      unitMultiplier
      images(quantity: 10) {
        imageId
        imageLabel
        imageTag
        imageUrl
        imageText
      }
      videos {
        videoUrl
      }
      sellers {
        sellerId
        sellerName
        addToCartLink
        sellerDefault
        commertialOffer {
          discountHighlights {
            name
          }
          teasers {
            name
            conditions {
              minimumQuantity
              parameters {
                name
                value
              }
            }
            effects {
              parameters {
                name
                value
              }
            }
          }
          Price
          ListPrice
          PriceWithoutDiscount
          RewardValue
          PriceValidUntil
          AvailableQuantity
          Tax
          CacheVersionUsedToCallCheckout
          Installments {
            Value
            InterestRate
            TotalValuePlusInterestRate
            NumberOfInstallments
            Name
          }
        }
      }
      variations {
        name
        values
      }
      kitItems {
        itemId
        amount
        product {
          productName
          productId
          description
          linkText
          categoryTree {
            id
            name
            href
          }
          categoryId
          brand
          properties {
            name
            values
          }
        }
        sku {
          itemId
          name
          referenceId {
            Key
            Value
          }
          images {
            imageId
            imageLabel
            imageTag
            imageUrl
            imageText
          }
          sellers {
            sellerId
            sellerName
            addToCartLink
            sellerDefault
            commertialOffer {
              discountHighlights {
                name
              }
              Price
              ListPrice
              PriceWithoutDiscount
              RewardValue
              PriceValidUntil
              AvailableQuantity
              Tax
              CacheVersionUsedToCallCheckout
              Installments(criteria: MAX) {
                Value
                InterestRate
                TotalValuePlusInterestRate
                NumberOfInstallments
                Name
              }
            }
          }
        }
      }
      attachments {
        id
        name
        required
      }
    }
    skuSpecifications {
      field {
        name
      }
      values {
        name
      }
    }
    itemMetadata {
      items {
        id
        name
        imageUrl
        seller
        assemblyOptions {
          id
          name
          required
          inputValues {
            label
            maxLength
            type
            domain
            defaultValue
          }
          composition {
            minQuantity
            maxQuantity
            items {
              id
              minQuantity
              maxQuantity
              priceTable
              seller
              initialQuantity
            }
          }
        }
      }
      priceTable {
        type
        values {
          id
          assemblyId
          price
        }
      }
    }
    productClusters {
      id
      name
    }
    clusterHighlights {
      id
      name
    }
  }
}
