query search(
  $query: String
  $map: String
  $rest: String
  $orderBy: String
  $priceRange: String
  $from: Int
  $to: Int
  $withFacets: Boolean = true
) {
  search(
    query: $query
    map: $map
    rest: $rest
    orderBy: $orderBy
    priceRange: $priceRange
    from: $from
    to: $to
  ) @context(provider: "vtex.store-graphql") {
    titleTag
    metaTagDescription
    facets @include(if: $withFacets) {
      Departments {
        Quantity
        Name
        Link
      }
      Brands {
        Quantity
        Name
        Link
      }
      SpecificationFilters {
        name
        facets {
          Quantity
          Name
          Link
        }
      }
      CategoriesTrees {
        Id
        Quantity
        Name
        Link
        href
        name
        Children {
          Id
          Quantity
          Name
          Link
          href
          name
          Children {
            Id
            Quantity
            Name
            Link
            href
            name
          }
        }
      }
      PriceRanges {
        Quantity
        Name
        Link
        Slug
      }
    }
    products {
      cacheId
      categories
      categoryTree {
        name
        href
      }
      productId
      description
      productName
      linkText
      brand
      link
      items {
        itemId
        name
        nameComplete
        complementName
        ean
        referenceId {
          Key
          Value
        }
        measurementUnit
        unitMultiplier
        images {
          cacheId
          imageId
          imageLabel
          imageTag
          imageUrl
          imageText
        }
        sellers {
          sellerId
          sellerName
          commertialOffer {
            discountHighlights {
              name
            }
            Price
            ListPrice
            PriceWithoutDiscount
            RewardValue
            PriceValidUntil
            AvailableQuantity
          }
        }
      }
      productClusters {
        id
        name
      }
    }
    recordsFiltered
  }
}
