query Session {
  getSession {
    id
    adminUserId
    impersonable
    adminUserEmail
    address {
      cacheId
      id
      addressId
      userId
      receiverName
      complement
      neighborhood
      country
      state
      number
      street
      geoCoordinates
      postalCode
      city
      reference
      addressName
      addressType
    }
    profile {
      id
      firstName
      lastName
      email
    }
    impersonate {
      profile {
        phone
        email
        lastName
        document
        firstName
      }
    }
  }
}
