query facets($facets: String) {
  facets(facets: $facets) {
    Departments {
      Quantity
      Name
      Link
    }
    Brands {
      Quantity
      Name
      Link
    }
    SpecificationFilters {
      name
      facets {
        Quantity
        Name
        Link
      }
    }
    CategoriesTrees {
      Quantity
      Name
      Children {
        Quantity
        Name
        Link
        Children {
          Quantity
          Name
          Link
        }
      }
    }
  }
}
