query orderForm {
  orderForm {
    cacheId
    orderFormId
    value
    isCheckedIn
    checkedInPickupPointId
    totalizers {
      id
      name
      value
    }
    items {
      id
      name
      imageUrl
      detailUrl
      skuName
      quantity
      sellingPrice
      listPrice
    }
    shippingData {
      address {
        id
        neighborhood
        complement
        number
        street
        postalCode
        city
        reference
        addressName
        addressType
      }
      availableAddresses {
        id
        neighborhood
        complement
        number
        street
        postalCode
        city
        reference
        addressName
        addressType
      }
    }
    clientProfileData {
      email
      firstName
    }
    storePreferencesData {
      countryCode
      currencyCode
      timeZone
    }
    pickupPoint {
      friendlyName
      id
      seller
      distance
      businessHours {
        openingTime
        closingTime
        dayOfWeek
      }
      address {
        id
        addressId
        street
        number
        receiverName
        complement
        neighborhood
        country
        state
        geoCoordinates
        postalCode
        city
        reference
        addressName
        addressType
      }
    }
  }
}
