query Product($slug: String) {
  product(slug: $slug) {
    cacheId
    productName
    productId
    description
    linkText
    categories
    categoryId
    categoriesIds
    brand
    properties {
      name,
      values
    },
    items {
      itemId
      name
      nameComplete
      complementName
      ean
      referenceId {
        Key
        Value
      }
      measurementUnit
      unitMultiplier
      images {
        imageId
        imageLabel
        imageTag
        imageUrl
        imageText
      }
      sellers {
        sellerId
        sellerName
        addToCartLink
        sellerDefault
        commertialOffer {
          Price
          ListPrice
          PriceWithoutDiscount
          RewardValue
          PriceValidUntil
          AvailableQuantity
          Tax
          CacheVersionUsedToCallCheckout
        }
      }
      variations {
        name
      }
    }
    benefits {
			featured
      id
      name
      items {
        benefitProduct {
          cacheId
					productName
          productId
          description
          linkText
          categories
          categoryId
          categoriesIds
          brand
          properties {
            name,
            values
          },
          items {
            itemId
            name
            nameComplete
            complementName
            ean
            referenceId {
              Key
              Value
            }
            measurementUnit
            unitMultiplier
            images {
              imageId
              imageLabel
              imageTag
              imageUrl
              imageText
            }
            sellers {
              sellerId
              sellerName
              addToCartLink
              sellerDefault
              commertialOffer {
                Price
                ListPrice
                PriceWithoutDiscount
                RewardValue
                PriceValidUntil
                AvailableQuantity
                Tax
                CacheVersionUsedToCallCheckout
              }
            }
            variations {
              name
            }
          }
        }
        discount
        minQuantity
      }
      teaserType
    }
  }
}
