query Product($slug: String) {
  product(slug: $slug) {
    cacheId
    productName
    productId
    description
    titleTag
    metaTagDescription
    linkText
    categories
    categoryId
    categoriesIds
    brand
    recommendations {
      view {
        cacheId
        productId
        productName
        description
        categories
        link
        linkText
        brand
        items {
          name
          itemId
          referenceId {
            Value
          }
          images {
            imageId
            imageLabel
            imageTag
            imageUrl
            imageText
          }
          sellers {
            sellerId
            sellerName
            addToCartLink
            sellerDefault
            commertialOffer {
              Price
              ListPrice
              PriceWithoutDiscount
              RewardValue
              PriceValidUntil
              AvailableQuantity
              Tax
              CacheVersionUsedToCallCheckout
              Installments {
                  Value
                  InterestRate
                  TotalValuePlusInterestRate
                  NumberOfInstallments
                  Name
              }
            }
          }
        }
      }
      buy {
        cacheId
        productId
        productName
        description
        categories
        link
        linkText
        brand
        items {
          name
          itemId
          referenceId {
            Value
          }
          images {
            imageId
            imageLabel
            imageTag
            imageUrl
            imageText
          }
          sellers {
            sellerId
            sellerName
            addToCartLink
            sellerDefault
            commertialOffer {
              Price
              ListPrice
              PriceWithoutDiscount
              RewardValue
              PriceValidUntil
              AvailableQuantity
              Tax
              CacheVersionUsedToCallCheckout
              Installments {
                  Value
                  InterestRate
                  TotalValuePlusInterestRate
                  NumberOfInstallments
                  Name
              }
            }
          }
        }
      }
      similars {
        cacheId
        productId
        productName
        description
        categories
        link
        linkText
        brand
        items {
          name
          itemId
          referenceId {
            Value
          }
          images {
            imageUrl
            imageTag
          }
          sellers {
            commertialOffer {
              Installments {
                Value
                InterestRate
                TotalValuePlusInterestRate
                NumberOfInstallments
                Name
              }
              Price
              ListPrice
            }
          }
        }
      }
    }
    properties {
      name
      values
    }
    items {
      itemId
      name
      nameComplete
      complementName
      ean
      referenceId {
        Key
        Value
      }
      measurementUnit
      unitMultiplier
      images {
        imageId
        imageLabel
        imageTag
        imageUrl
        imageText
      }
      sellers {
        sellerId
        sellerName
        addToCartLink
        sellerDefault
        commertialOffer {
          Price
          ListPrice
          PriceWithoutDiscount
          RewardValue
          PriceValidUntil
          AvailableQuantity
          Tax
          CacheVersionUsedToCallCheckout
          Installments {
              Value
              InterestRate
              TotalValuePlusInterestRate
              NumberOfInstallments
              Name
          }
        }
      }
      variations {
        name
      }
      kitItems {
        itemId
        amount
        product {
          productName
          productId
    			description
    			linkText
    			categories
    			categoryId
    			categoriesIds
    			brand
    			properties {
      			name
      			values
    			}
        }
        sku {
          itemId
          name
          referenceId {
            Key
            Value
          }
          images {
            imageId
            imageLabel
            imageTag
            imageUrl
            imageText
          }
          sellers {
            sellerId
            sellerName
            addToCartLink
            sellerDefault
            commertialOffer {
              Price
              ListPrice
              PriceWithoutDiscount
              RewardValue
              PriceValidUntil
              AvailableQuantity
              Tax
              CacheVersionUsedToCallCheckout
              Installments {
                  Value
                  InterestRate
                  TotalValuePlusInterestRate
                  NumberOfInstallments
                  Name
              }
            }
          }
        }
      }
    }
    benefits {
			featured
      id
      name
      items {
        benefitProduct {
          cacheId
					productName
          productId
          description
          linkText
          categories
          categoryId
          categoriesIds
          brand
          properties {
            name,
            values
          },
          items {
            itemId
            name
            nameComplete
            complementName
            ean
            referenceId {
              Key
              Value
            }
            measurementUnit
            unitMultiplier
            images {
              imageId
              imageLabel
              imageTag
              imageUrl
              imageText
            }
            sellers {
              sellerId
              sellerName
              addToCartLink
              sellerDefault
              commertialOffer {
                Price
                ListPrice
                PriceWithoutDiscount
                RewardValue
                PriceValidUntil
                AvailableQuantity
                Tax
                CacheVersionUsedToCallCheckout
                Installments {
                    Value
                    InterestRate
                    TotalValuePlusInterestRate
                    NumberOfInstallments
                    Name
                }
              }
            }
            variations {
              name
            }
          }
        }
        discount
        minQuantity
      }
      teaserType
    }
    productClusters{
      id
      name
    }
    clusterHighlights{
      id
      name
    }
  }
}
