query Products($query: String) {
  products(query: $query) {
    cacheId
    productId
    productName
    linkText
    description
    categories
    items {
      itemId
      name
      nameComplete
      complementName
      ean
      referenceId {
        Key
        Value
      }
      measurementUnit
      unitMultiplier
      images {
        imageId
        imageLabel
        imageTag
        imageUrl
        imageText
      }
      sellers {
        sellerId
        sellerName
        commertialOffer {
          Price
          ListPrice
          PriceWithoutDiscount
          RewardValue
          PriceValidUntil
          AvailableQuantity
        }
      }
    }
  }
}
