fragment product on Product {
  cacheId
  productId
  productName
  linkText
  titleTag
  metaTagDescription
  description
  categories
  items {
    itemId
    name
    nameComplete
    complementName
    ean
    referenceId {
      Key
      Value
    }
    measurementUnit
    unitMultiplier
    images {
      imageId
      imageLabel
      imageTag
      imageUrl
      imageText
    }
    sellers {
      sellerId
      sellerName
      commertialOffer {
        Price
        ListPrice
        PriceWithoutDiscount
        RewardValue
        PriceValidUntil
        AvailableQuantity
      }
    }
    attachments {
      id
      name
      required
    }
  }
}
