query search($query: String, $map: String, $rest: String, $orderBy: String, $from: Int, $to: Int) {
  search(query: $query, map: $map, rest: $rest, orderBy: $orderBy, from: $from, to: $to) {
    titleTag
    metaTagDescription
    facets {
      Departments {
        Quantity
        Name
        Link
      }
      Brands {
        Quantity
        Name
        Link
      }
      SpecificationFilters {
        name
        facets {
          Quantity
          Name
          Link
        }
      }
      CategoriesTrees {
        Quantity
        Name
        Link
        Children {
          Quantity
          Name
          Link
          Children {
            Quantity
            Name
            Link
          }
        }
      }
      PriceRanges {
        Quantity
        Name
        Link
      }
    } 
    products {
      productId
      productName
      linkText
      description
      brand
      link
      items {
        itemId
        name
        nameComplete
        complementName
        ean
        referenceId {
          Key
          Value
        }
        measurementUnit
        unitMultiplier
        images {
          imageId
          imageLabel
          imageTag
          imageUrl
          imageText
        }
        sellers {
          sellerId
          sellerName
          commertialOffer {
            Price
            ListPrice
            PriceWithoutDiscount
            RewardValue
            PriceValidUntil
            AvailableQuantity
          }
        }
      }
      productClusters {
        name
      }
    }
    recordsFiltered
  }
}
