export default {
  cacheId: '3335fe72057045398dd28bd2fa203b21',
  orderFormId: '3335fe72057045398dd28bd2fa203b21',
  value: 0,
  totalizers: [
    {
      id: 'Items',
      name: 'Items Total',
      value: 0,
      __typename: 'vtex_storegraphql_2_51_0_Totalizer',
    },
    {
      id: 'Shipping',
      name: 'Shipping Total',
      value: 0,
      __typename: 'vtex_storegraphql_2_51_0_Totalizer',
    },
  ],
  items: [],
  shippingData: {
    address: {
      id: null,
      neighborhood: 'Botafogo',
      complement: '',
      number: '300',
      street: 'Praia de Botafogo',
      postalCode: '22250-040',
      city: 'Rio de Janeiro',
      reference: null,
      addressName: null,
      addressType: 'residential',
      __typename: 'vtex_storegraphql_2_51_0_Address',
    },
    availableAddresses: [
      {
        id: null,
        neighborhood: 'Botafogo',
        complement: '',
        number: '300',
        street: 'Praia de Botafogo',
        postalCode: '22250-040',
        city: 'Rio de Janeiro',
        reference: null,
        addressName: null,
        addressType: 'residential',
        __typename: 'vtex_storegraphql_2_51_0_Address',
      },
    ],
    __typename: 'vtex_storegraphql_2_51_0_OrderFormShippingData',
  },
  clientProfileData: null,
  storePreferencesData: {
    countryCode: 'BRA',
    currencyCode: 'BRL',
    timeZone: 'E. South America Standard Time',
  },
  itemMetadata: {
    items: [],
  },
}
