export const product = {
  cacheId: 'my-prod',
  productName: 'Super cellphone',
  productId: '111',
  description: 'teste',
  titleTag: 'Title',
  metaTagDescription: 'Meta',
  linkText: 'my-prod',
  productReference: '1',
  categoryId: '1',
  categories: [
    '/Tecnologia/Celulares/Smartphones/',
    '/Tecnologia/Celulares/',
    '/Tecnologia/',
  ],
  brand: 'HUAWEI',
  brandId: 1212,
  items: [
    {
      itemId: '100304479',
      name: 'Super cell item',
      nameComplete: 'super cell item complete',
      complementName: '',
      ean: '111111',
      referenceId: null,
      measurementUnit: 'un',
      unitMultiplier: 1,
      images: [
        {
          imageId: '111',
          imageLabel: null,
          imageTag: '',
          imageUrl: 'myimage.com',
          imageText: null,
        },
      ],
      videos: [],
      sellers: [
        {
          sellerId: '1',
          sellerName: 'Seller sport',
          addToCartLink: 'lala.com',
          sellerDefault: false,
          commertialOffer: {
            discountHighlights: [],
            teasers: [],
            Price: 899000,
            ListPrice: 999000,
            PriceWithoutDiscount: 899000,
            RewardValue: 0,
            PriceValidUntil: '2020-09-20T19:47:56.9849658Z',
            AvailableQuantity: 5,
            Tax: 0,
          },
        },
        {
          sellerId: '2',
          sellerName: 'seller mundo movil',
          addToCartLink: 'lala.com',
          sellerDefault: false,
          commertialOffer: {
            discountHighlights: [],
            teasers: [],
            Price: 924330,
            ListPrice: 1200000,
            PriceWithoutDiscount: 924330,
            RewardValue: 0,
            PriceValidUntil: '2020-09-20T19:47:56.9613527Z',
            AvailableQuantity: 5,
            Tax: 0,
          },
        },
        {
          sellerId: '3',
          sellerName: 'celu store',
          addToCartLink: '',
          sellerDefault: false,
          commertialOffer: {
            discountHighlights: [],
            teasers: [],
            Price: 898999,
            ListPrice: 999998,
            PriceWithoutDiscount: 898999,
            RewardValue: 0,
            PriceValidUntil: '2020-09-20T19:47:56.9593497Z',
            AvailableQuantity: 10,
            Tax: 0,
          },
        },
        {
          sellerId: '3',
          sellerName: 'fake seller',
          addToCartLink: '',
          sellerDefault: false,
          commertialOffer: {
            discountHighlights: [],
            teasers: [],
            Price: 955900,
            ListPrice: 1219900,
            PriceWithoutDiscount: 955900,
            RewardValue: 0,
            PriceValidUntil: '2020-09-20T19:47:56.9559171Z',
            AvailableQuantity: 20,
            Tax: 0,
          },
        },
        {
          sellerId: '4',
          sellerName: 'another fake seller',
          addToCartLink: 'lala.com',
          sellerDefault: true,
          commertialOffer: {
            discountHighlights: [],
            teasers: [],
            Price: 869900,
            ListPrice: 1199900,
            PriceWithoutDiscount: 869900,
            RewardValue: 0,
            PriceValidUntil: '2020-09-20T19:47:56.9502296Z',
            AvailableQuantity: 9,
            Tax: 0,
          },
        },
        {
          sellerId: '11829',
          sellerName: 'multisistemas',
          addToCartLink: '',
          sellerDefault: false,
          commertialOffer: {
            discountHighlights: [],
            teasers: [],
            Price: 899000,
            ListPrice: 1100000,
            PriceWithoutDiscount: 899000,
            RewardValue: 0,
            PriceValidUntil: '2020-09-20T19:47:56.9596485Z',
            AvailableQuantity: 9,
            Tax: 0,
          },
        },
        {
          sellerId: '1',
          sellerName: 'last seller',
          addToCartLink: '',
          sellerDefault: false,
          commertialOffer: {
            discountHighlights: [],
            teasers: [],
            Price: 0,
            ListPrice: 0,
            PriceWithoutDiscount: 0,
            RewardValue: 0,
            PriceValidUntil: null,
            AvailableQuantity: 0,
            Tax: 0,
          },
        },
      ],
      variations: [],
      kitItems: [],
      attachments: [],
    },
  ],
}
